name: Build YTweaks .deb(s) packages
on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        type: choice
        options:
          - 16.5
          - 17.5
          - 18.6
        required: true
        default: 16.5

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTweaks .deb(s) packages
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV 

      - name: Get Theos commit hash
        id: get_theos_commit
        run: |
          get_commit_hash() {
            local repo_url=$1
            git ls-remote "$repo_url" HEAD | awk '{print substr($1,1,7)}'
          }
          
          THEOS_COMMIT=$(get_commit_hash "https://github.com/theos/theos.git")
          echo "theos=$THEOS_COMMIT" >> $GITHUB_OUTPUT
          echo "Theos commit: $THEOS_COMMIT"

      - name: Cache Theos
        id: theos
        uses: actions/cache@v5.0.1
        with:
          path: theos/
          key: theos_${{ steps.get_theos_commit.outputs.theos }}_${{ inputs.sdk_version }}
    
      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        run: git clone --quiet --depth=1 --recurse-submodules https://github.com/theos/theos.git

      - name: Download iOS 16.5 SDK
        if: steps.theos.outputs.cache-hit != 'true' && inputs.sdk_version == '16.5'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Download iOS 17.5 SDK
        if: steps.theos.outputs.cache-hit != 'true' && inputs.sdk_version == '17.5'
        run: |
          git clone --quiet --no-tags --single-branch --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-17.5-SDK.git
          cd iOS-17.5-SDK
          git sparse-checkout set --no-cone iPhoneOS17.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Download iOS 18.6 SDK
        if: steps.theos.outputs.cache-hit != 'true' && inputs.sdk_version == '18.6'
        run: |
          git clone --quiet --no-tags --single-branch --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-18.6-SDK.git
          cd iOS-18.6-SDK
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Clone YouTubeHeader
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            echo "YouTubeHeader exists. Pulling latest changes..."
            cd $THEOS/include/YouTubeHeader
            git pull
          else
            echo "YouTubeHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi
          
      - name: Clone PSHeader
        run: |
          if [ -d "$THEOS/include/PSHeader" ]; then
            echo "PSHeader exists. Pulling latest changes..."
            cd $THEOS/include/PSHeader
            git pull
          else
            echo "PSHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi

      - name: Build YTweaks
        run: |
          echo "YTWEAKS_VERSION=$(grep '^Version:' control | cut -d ' ' -f2)" >> $GITHUB_ENV
          echo "Building YTweaks..."
          make clean package DEBUG=0 FINALPACKAGE=1
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}

      - name: Rename DEB files
        run: |
          mv "com.fosterbarnes.ytweaks_${{ env.YTWEAKS_VERSION }}_iphoneos-arm.deb" "YTweaks v${{ env.YTWEAKS_VERSION }} Rootful.deb"
          mv "com.fosterbarnes.ytweaks_${{ env.YTWEAKS_VERSION }}_iphoneos-arm64.deb" "YTweaks v${{ env.YTWEAKS_VERSION }} Rootless.deb"
          echo "Renamed DEB files to YTweaks v${{ env.YTWEAKS_VERSION }} Rootful.deb and YTweaks v${{ env.YTWEAKS_VERSION }} Rootless.deb"

      - name: Output .deb(s)
        uses: actions/upload-artifact@v6
        with:
         name: YTweaks v${{ env.YTWEAKS_VERSION }}
         path: ${{ github.workspace }}/*.deb
         if-no-files-found: error
         overwrite: true

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: v${{ env.YTWEAKS_VERSION }}
          name: YTweaks v${{ env.YTWEAKS_VERSION }}
          files: ${{ github.workspace }}/*.deb
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
